# Bike Sharing Demand Forecasting Project   
0) Create virtual environment 
1) Part 1 - Data Ingestion from Azure Blob Storage to Bronze folder 
2) Part 2 - Data Transformation and Cleaning in Silver folder, then finally data is stored in Gold folder. 
3) Create Data Modelling and Visualization using PowerBI 
4) Leverage ML concepts to build prediction model ( EDA, Feature Selection, Model development, Evaluation, Deployment). 
5) Build MVP streamlit app and FastAPI (optional) for end users for predictions

In [1]:
# Check PySpark Version
import pyspark 
print("PySpark Version:", pyspark.__version__)

PySpark Version: 3.4.1

In [2]:
# Simple Spark Session Test
from pyspark.sql import SparkSession
spark = SparkSession.builder.getOrCreate()
spark.range(5).show()

+---+
| id|
+---+
|  0|
|  1|
|  2|
|  3|
|  4|
+---+

#  Bronze Layer Construction
1. Data Ingestion from Azure Blob Storage 

 a) Import libraries 
 b) Set Connect to Azure Blob Storage API to retieve the files from container 
 c) Validate Files exists in Blob Storage, check sizes and Schema of the files
 d) Load to bronze folder path

In [3]:
# import the necessary libraries 

from pyspark.sql import SparkSession
import os
from dotenv import load_dotenv
from azure.identity import ClientSecretCredential 
from azure.storage.blob import BlobServiceClient
from azure.keyvault.secrets import SecretClient 
from pyspark.sql.functions import lit, current_date
import pandas as pd 
import io
import time
from azure.core.exceptions import ResourceNotFoundError
from datetime import datetime
import pyarrow as pa
import pyarrow.parquet as pq
import logging 
import holidays

In [4]:
load_dotenv()

True

In [5]:
# Load environment variables
client_id=os.environ["AZURE_CLIENT_ID"]
tenant_id=os.environ["AZURE_TENANT_ID"] 
client_secret=os.environ["AZURE_CNT_SECRET"]
vault_url=os.environ["AZURE_VAULT_URL"]
container_name=os.environ["AZURE_CONTAINER_NAME"]
bronze_folder_path=os.environ["BRONZE_FOLDER_PATH"]
silver_folder_path=os.environ["SILVER_FOLDER_PATH"]
gold_folder_path=os.environ["GOLD_FOLDER_PATH"]
bi_log_folder_path=os.environ["BI_LOG_FOLDER_PATH"]

credentials = ClientSecretCredential(
    tenant_id=tenant_id,
    client_id=client_id,
    client_secret=client_secret 
) 

print("Connection to Azure blob storage successfully.")

Connection to Azure blob storage successfully.

In [6]:
# Create logs folder if missing and remove verbose logs
logging.getLogger("azure").setLevel(logging.WARNING)
os.makedirs(bi_log_folder_path, exist_ok=True)

# Log file path
log_file = os.path.join(bi_log_folder_path, "bi_pipeline.log")
print(log_file)

# Configure logger
logging.basicConfig(
    filename=log_file,
    format="%(asctime)s - %(levelname)s - %(message)s",
    level=logging.INFO,
    filemode="a"   # append to log file
)

logging.info("🚀 BI Pipeline execution started.")

D:\Python\AUSTRACT_Project\end_to_end_bike_sharing_data_project\business_intelligence\logs\bi_pipeline.log

In [7]:
# Create blob service client
logging.info("Connecting to Azure Blob Storage...")
try:
    blob_service_client = BlobServiceClient(
    account_url=vault_url,
    credential=credentials    # your ClientSecretCredential  
    )
    container_client = blob_service_client.get_container_client(container_name)
    logging.info("Connected to Azure Blob Storage successfully.")
except Exception as e:
    logging.error(f"Failed to connect to Azure Blob Storage: {e}")
    raise

In [8]:
def load_validated_csv(blob_name: str) -> pd.DataFrame:
    """
    Validates blob existence and size, then loads CSV into pandas.
    Prevents loading if blob is missing or empty.
    """
    # Step 1 — Validate existence and size
    try:
        blob_client = container_client.get_blob_client(blob_name)
        props = blob_client.get_blob_properties()
    except ResourceNotFoundError:
        raise FileNotFoundError(f"Missing required file: {blob_name}")

    if props.size == 0:
        raise ValueError(f"File '{blob_name}' exists but is EMPTY")

    print(f"{blob_name} validated (size = {props.size} bytes)")

    # Step 2 — Load CSV into memory
    data = blob_client.download_blob().readall()
    df = pd.read_csv(io.BytesIO(data))

    print(f"Loaded {blob_name}: {df.shape[0]} rows, {df.shape[1]} columns")
    return df

In [9]:
# List of required file
logging.info("Validating required files...")
try:
    bikesharing_df = load_validated_csv("bikesharing.csv")
    dates_df = load_validated_csv("dates.csv")
    logging.info("File validation successful.")
except Exception as e:
    logging.error(f"File validation failed: {e}")
    raise

bikesharing.csv validated (size = 1151577 bytes)
Loaded bikesharing.csv: 17379 rows, 17 columns
dates.csv validated (size = 52302 bytes)
Loaded dates.csv: 1046 rows, 9 columns

In [10]:
# Check schema of both the files

expected_bikesharing_schema = dict(zip(bikesharing_df.columns, bikesharing_df.dtypes.astype(str)))
print(expected_bikesharing_schema)

expected_dates_schema = dict(zip(dates_df.columns, dates_df.dtypes.astype(str)))
print(expected_dates_schema)

{'index': 'int64', 'date': 'object', 'season': 'int64', 'year': 'int64', 'month': 'int64', 'hour': 'int64', 'holiday': 'int64', 'weekday': 'int64', 'workingday': 'int64', 'weather': 'int64', 'temp': 'float64', 'atemp': 'float64', 'humidity': 'float64', 'windspeed': 'float64', 'casual': 'int64', 'registered': 'int64', 'demand': 'int64'}
{'date': 'object', 'datekey': 'int64', 'day': 'int64', 'month': 'int64', 'month_name': 'object', 'year': 'int64', 'weekday': 'object', 'weekofyear': 'int64', 'is_weekend': 'int64'}

In [11]:
def validate_schema(df: pd.DataFrame, expected_schema: dict, file_name: str):
    """
    Validate that the dataframe matches the expected schema:
    - Same columns
    - Same dtypes
    """
    # Check columns match
    df_cols = list(df.columns)
    expected_cols = list(expected_schema.keys())

    if df_cols != expected_cols:
        raise ValueError(
            f"❌ Schema mismatch in {file_name}\n"
            f"Expected columns: {expected_cols}\n"
            f"Found columns:    {df_cols}"
        )

    # Check data types match
    for col, expected_type in expected_schema.items():
        actual_type = str(df[col].dtype)

        if actual_type != expected_type:
            raise ValueError(
                f"❌ Datatype mismatch in {file_name} for column '{col}'\n"
                f"Expected: {expected_type}, Found: {actual_type}"
            )

    print(f"Schema validated successfully for {file_name}")

In [12]:
# Validate schemas from function
logging.info("Validating schema...") 
try:
    validate_schema(bikesharing_df, expected_bikesharing_schema, "bikesharing.csv")
    validate_schema(dates_df, expected_dates_schema, "dates.csv")
    logging.info("Schema validation successful.")
except Exception as e:
    logging.error(f"Schema validation failed: {e}")
    raise

Schema validated successfully for bikesharing.csv
Schema validated successfully for dates.csv

In [13]:
# Add data extraction timestamp column for both dataframes and save to bronze folder

current_ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
bikesharing_df["data_extract_ts"] = current_ts
dates_df["data_extract_ts"] = current_ts

In [14]:
# Review the final dataframes   
display(bikesharing_df.head())
display(dates_df.head())

,index,date,season,year,month,hour,holiday,weekday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,demand,data_extract_ts
0,1,1/01/2023,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,3,13,16,2025-11-16 08:20:51
1,2,1/01/2023,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0,8,32,40,2025-11-16 08:20:51
2,3,1/01/2023,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0,5,27,32,2025-11-16 08:20:51
3,4,1/01/2023,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0,3,10,13,2025-11-16 08:20:51
4,5,1/01/2023,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0,0,1,1,2025-11-16 08:20:51

,date,datekey,day,month,month_name,year,weekday,weekofyear,is_weekend,data_extract_ts
0,2023-01-01,20230101,1,1,January,2023,Sunday,52,1,2025-11-16 08:20:51
1,2023-01-02,20230102,2,1,January,2023,Monday,1,0,2025-11-16 08:20:51
2,2023-01-03,20230103,3,1,January,2023,Tuesday,1,0,2025-11-16 08:20:51
3,2023-01-04,20230104,4,1,January,2023,Wednesday,1,0,2025-11-16 08:20:51
4,2023-01-05,20230105,5,1,January,2023,Thursday,1,0,2025-11-16 08:20:51

In [15]:
# save dataframes as parquet files locally and upload to bronze folder in local directory

def save_parquet_local(df, file_path):
    # Create folder if not exists
    folder = os.path.dirname(file_path)
    os.makedirs(folder, exist_ok=True)
    # Save parquet
    table = pa.Table.from_pandas(df)
    pq.write_table(table, file_path)
    rel_path = os.path.relpath(file_path)
    print(f"Saved to local file directory: {rel_path}")

In [16]:
logging.info("Saving datasets to Bronze layer...")
try:
    save_parquet_local(bikesharing_df, bronze_folder_path + "/bikesharing.parquet")
    save_parquet_local(dates_df,       bronze_folder_path + "/dates.parquet") 
    logging.info("Datasets saved to Bronze layer successfully.")
except Exception as e:
    logging.error(f"Failed to save datasets to Bronze layer: {e}")
    raise

Saved to local file directory: ..\business_intelligence\data\1.bronze\bikesharing.parquet
Saved to local file directory: ..\business_intelligence\data\1.bronze\dates.parquet

# Silver Layer Construction  
2) Data Transformation and Cleaning

In [17]:
# Extract and read the parquet file from bronze folder to validate 

df_bikesharing = pd.read_parquet(bronze_folder_path + "/bikesharing.parquet") 
df_dates = pd.read_parquet(bronze_folder_path + "/dates.parquet")

# Construction dim table from df_bikesharing tbl helpful for analysis

In [18]:
# First create dim_season tables from bikesharing dataframe 

def season_dim_table(df: pd.DataFrame) -> pd.DataFrame:
    season_dim = df[['season']].drop_duplicates().reset_index(drop=True)
    season_dim['season_key'] = season_dim.index + 1
    season_dim ['season_description'] = season_dim['season'].map({1: 'Winter', 2: 'Spring', 3: 'Summer', 4: 'Autumn'})
    return season_dim[['season_key', 'season_description']]

In [19]:
# Check the season dimension table
dim_season_tbl_processed = season_dim_table(df_bikesharing)
dim_season_tbl_processed

   season_key season_description
0           1             Winter
1           2             Spring
2           3             Summer
3           4             Autumn

In [20]:
# Create weather dimension table from bikesharing dataframe

def weather_dim_table(df: pd.DataFrame) -> pd.DataFrame:
    weather_dim = df[['weather']].drop_duplicates().reset_index(drop=True)
    weather_dim['weather_key'] = weather_dim.index + 1
    weather_dim ['weather_description'] = weather_dim['weather'].map({1: 'Clear', 2: 'Mist + Cloudy', 3: 'Light Snow/Rain', 4: 'Heavy Rain/Snow'})
    return weather_dim[['weather_key','weather_description']]

In [21]:
# Check the season dimension table
dim_weather_tbl_processed = weather_dim_table(df_bikesharing)
dim_weather_tbl_processed

   weather_key weather_description
0            1               Clear
1            2       Mist + Cloudy
2            3     Light Snow/Rain
3            4     Heavy Rain/Snow

In [22]:
def hour_dim_table(df: pd.DataFrame) -> pd.DataFrame:
    # Unique hours from the dataset
    hour_dim = df[['hour']].drop_duplicates().reset_index(drop=True)
    hour_dim['hour_key'] = hour_dim.index
    
    # Hour bin classification
    def assign_hour_bin(h):
        if 0 <= h <= 4:
            return '0-4'
        elif 5 <= h <= 7:
            return '5-7'
        elif 8 <= h <= 17:
            return '8-17'
        elif 18 <= h <= 20:
            return '18-20'
        else:
            return '21-23'

    # Hour description classification
    def assign_hour_description(h):
        if 0 <= h <= 4:
            return 'Late Night'
        elif 5 <= h <= 7:
            return 'Early Morning'
        elif 8 <= h <= 17:
            return 'Office Hours'
        elif 18 <= h <= 20:
            return 'Evening'
        else:
            return 'Night'

    hour_dim['hour_bin'] = hour_dim['hour'].apply(assign_hour_bin)
    hour_dim['hour_description'] = hour_dim['hour'].apply(assign_hour_description)

    return hour_dim[['hour_key', 'hour', 'hour_bin', 'hour_description']]

# Check the hour dimension table

In [ ]:
dim_hour_tbl_processed = hour_dim_table(df_bikesharing)
dim_hour_tbl_processed

    hour_key  hour hour_bin hour_description
0          0     0      0-4       Late Night
1          1     1      0-4       Late Night
2          2     2      0-4       Late Night
3          3     3      0-4       Late Night
4          4     4      0-4       Late Night
5          5     5      5-7    Early Morning
6          6     6      5-7    Early Morning
7          7     7      5-7    Early Morning
8          8     8     8-17     Office Hours
9          9     9     8-17     Office Hours
10        10    10     8-17     Office Hours
11        11    11     8-17     Office Hours
12        12    12     8-17     Office Hours
13        13    13     8-17     Office Hours
14        14    14     8-17     Office Hours
15        15    15     8-17     Office Hours
16        16    16     8-17     Office Hours
17        17    17     8-17     Office Hours
18        18    18    18-20          Evening
19        19    19    18-20          Evening
20        20    20    18-20          Evening
21        21    21    21-23            Night
22        22    22    21-23            Night
23        23    23    21-23            Night

# Construct temperature, humidity, and windspeed dimension tables

In [ ]:
def temp_humidity_windspeed_dim_table(df: pd.DataFrame):
    # Temp dimension
    temp_dim = df[['temp']].drop_duplicates().reset_index(drop=True)
    temp_dim['temp_key'] = temp_dim.index + 1
    temp_dim['temp_celsius'] = temp_dim['temp'] * 41

    # Round temperature (IMPORTANT FIX)
    temp_dim['temp_celsius_round'] = temp_dim['temp_celsius'].round().astype(int)

    def assign_temp_bin(c):
        if c <= 9:
            return "0-9°C"
        elif 10 <= c <= 18:
            return "10-18°C"
        elif 19 <= c <= 24:
            return "19-24°C"
        elif 25 <= c <= 30:
            return "25-30°C"
        elif 31 <= c <= 35:
            return "31-35°C"
        else:
            return "36°C+"

    def assign_temp_category(c):
        if c <= 9:
            return "Very Cold"
        elif 10 <= c <= 18:
            return "Cold"
        elif 19 <= c <= 24:
            return "Mild"
        elif 25 <= c <= 30:
            return "Warm"
        elif 31 <= c <= 35:
            return "Hot"
        else:
            return "Very Hot"

    # Apply bins to rounded temp
    temp_dim['temp_bin'] = temp_dim['temp_celsius_round'].apply(assign_temp_bin)
    temp_dim['temp_category'] = temp_dim['temp_celsius_round'].apply(assign_temp_category)

    # Humidity (UCI = 'hum')
    humidity_dim = df[['humidity']].drop_duplicates().reset_index(drop=True)
    humidity_dim['humidity_key'] = humidity_dim.index + 1
    humidity_dim['humidity_percentage'] = (humidity_dim['humidity'] * 100).round(1)

    # Categorization
    def assign_humidity_category(h):
        if h <= 29:
            return "Dry"
        elif 30 <= h <= 59:
            return "Comfortable"
        elif 60 <= h <= 79:
            return "Humid"
        else:
            return "Very Humid"

    def assign_humidity_bin(h):
        if h <= 29:
            return "0-29%"
        elif 30 <= h <= 59:
            return "30-59%"
        elif 60 <= h <= 79:
            return "60-79%"
        else:
            return "80-100%"

    humidity_dim['humidity_bin'] = humidity_dim['humidity_percentage'].apply(assign_humidity_bin)
    humidity_dim['humidity_category'] = humidity_dim['humidity_percentage'].apply(assign_humidity_category)

    # Windspeed
    windspeed_dim = df[['windspeed']].drop_duplicates().reset_index(drop=True)
    windspeed_dim['windspeed_key'] = windspeed_dim.index + 1
    windspeed_dim['windspeed_kmh'] = (windspeed_dim['windspeed'] * 67).round(1)

        # Categorization
    def assign_wind_category(w):
        if w <= 5:
            return "Calm"
        elif 6 <= w <= 20:
            return "Breeze"
        elif 21 <= w <= 39:
            return "Windy"
        elif 40 <= w <= 60:
            return "Strong Wind"
        else:
            return "Stormy"

    def assign_wind_bin(w):
        if w <= 5:
            return "0-5 km/h"
        elif 6 <= w <= 20:
            return "6-20 km/h"
        elif 21 <= w <= 39:
            return "21-39 km/h"
        elif 40 <= w <= 60:
            return "40-60 km/h"
        else:
            return "60 km/h+"

    windspeed_dim['windspeed_bin'] = windspeed_dim['windspeed_kmh'].apply(assign_wind_bin)
    windspeed_dim['windspeed_category'] = windspeed_dim['windspeed_kmh'].apply(assign_wind_category)

    return (
        temp_dim[['temp_key', 'temp', 'temp_celsius', 'temp_celsius_round', 'temp_bin', 'temp_category']],
        humidity_dim[['humidity_key', 'humidity', 'humidity_percentage', 'humidity_bin', 'humidity_category']],
        windspeed_dim[['windspeed_key', 'windspeed', 'windspeed_kmh', 'windspeed_bin', 'windspeed_category']]
    )

In [25]:
# Check the temp , hum, wind dimension table
dim_temp_tbl_processed, dim_humidity_tbl_processed, dim_windspeed_tbl_processed = temp_humidity_windspeed_dim_table(df_bikesharing)
dim_temp_tbl_processed, dim_humidity_tbl_processed, dim_windspeed_tbl_processed

(    temp_key  temp  temp_celsius  temp_celsius_round temp_bin temp_category
 0          1  0.24          9.84                  10  10-18°C          Cold
 1          2  0.22          9.02                   9    0-9°C     Very Cold
 2          3  0.20          8.20                   8    0-9°C     Very Cold
 3          4  0.32         13.12                  13  10-18°C          Cold
 4          5  0.38         15.58                  16  10-18°C          Cold
 5          6  0.36         14.76                  15  10-18°C          Cold
 6          7  0.42         17.22                  17  10-18°C          Cold
 7          8  0.46         18.86                  19  19-24°C          Mild
 8          9  0.44         18.04                  18  10-18°C          Cold
 9         10  0.40         16.40                  16  10-18°C          Cold
 10        11  0.34         13.94                  14  10-18°C          Cold
 11        12  0.30         12.30                  12  10-18°C          Cold
 12        13  0.26         10.66                  11  10-18°C          Cold
 13        14  0.16          6.56                   7    0-9°C     Very Cold
 14        15  0.14          5.74                   6    0-9°C     Very Cold
 15        16  0.18          7.38                   7    0-9°C     Very Cold
 16        17  0.12          4.92                   5    0-9°C     Very Cold
 17        18  0.28         11.48                  11  10-18°C          Cold
 18        19  0.10          4.10                   4    0-9°C     Very Cold
 19        20  0.08          3.28                   3    0-9°C     Very Cold
 20        21  0.06          2.46                   2    0-9°C     Very Cold
 21        22  0.04          1.64                   2    0-9°C     Very Cold
 22        23  0.02          0.82                   1    0-9°C     Very Cold
 23        24  0.52         21.32                  21  19-24°C          Mild
 24        25  0.56         22.96                  23  19-24°C          Mild
 25        26  0.58         23.78                  24  19-24°C          Mild
 26        27  0.60         24.60                  25  25-30°C          Warm
 27        28  0.48         19.68                  20  19-24°C          Mild
 28        29  0.54         22.14                  22  19-24°C          Mild
 29        30  0.50         20.50                  20  19-24°C          Mild
 30        31  0.66         27.06                  27  25-30°C          Warm
 31        32  0.64         26.24                  26  25-30°C          Warm
 32        33  0.62         25.42                  25  25-30°C          Warm
 33        34  0.68         27.88                  28  25-30°C          Warm
 34        35  0.70         28.70                  29  25-30°C          Warm
 35        36  0.74         30.34                  30  25-30°C          Warm
 36        37  0.76         31.16                  31  31-35°C           Hot
 37        38  0.72         29.52                  30  25-30°C          Warm
 38        39  0.78         31.98                  32  31-35°C           Hot
 39        40  0.82         33.62                  34  31-35°C           Hot
 40        41  0.80         32.80                  33  31-35°C           Hot
 41        42  0.86         35.26                  35  31-35°C           Hot
 42        43  0.88         36.08                  36    36°C+      Very Hot
 43        44  0.90         36.90                  37    36°C+      Very Hot
 44        45  0.84         34.44                  34  31-35°C           Hot
 45        46  0.92         37.72                  38    36°C+      Very Hot
 46        47  0.94         38.54                  39    36°C+      Very Hot
 47        48  0.96         39.36                  39    36°C+      Very Hot
 48        49  0.98         40.18                  40    36°C+      Very Hot
 49        50  1.00         41.00                  41    36°C+      Very Hot,
     humidity_key  humidity  humidity_percentage humidity_bin humidity_category
 0              1      0.81                 81.0      80-100%        Very Humid
 1              2      0.80                 80.0      80-100%        Very Humid
 2              3      0.75                 75.0       60-79%             Humid
 3              4      0.86                 86.0      80-100%        Very Humid
 4              5      0.76                 76.0       60-79%             Humid
 ..           ...       ...                  ...          ...               ...
 84            85      0.84                 84.0      80-100%        Very Humid
 85            86      0.89                 89.0      80-100%        Very Humid
 86            87      0.79                 79.0       60-79%             Humid
 87            88      0.97                 97.0      80-100%        Very Humid
 88            89      0.91                 91.0      80-100%        Very Humid

 [89 rows x 5 columns],
     windspeed_key  windspeed  windspeed_kmh windspeed_bin windspeed_category
 0               1     0.0000            0.0      0-5 km/h               Calm
 1               2     0.0896            6.0     6-20 km/h             Breeze
 2               3     0.2537           17.0     6-20 km/h             Breeze
 3               4     0.2836           19.0     6-20 km/h             Breeze
 4               5     0.2985           20.0     6-20 km/h             Breeze
 5               6     0.1940           13.0     6-20 km/h             Breeze
 6               7     0.2239           15.0     6-20 km/h             Breeze
 7               8     0.1343            9.0     6-20 km/h             Breeze
 8               9     0.1642           11.0     6-20 km/h             Breeze
 9              10     0.3284           22.0    21-39 km/h              Windy
 10             11     0.4478           30.0    21-39 km/h              Windy
 11             12     0.3582           24.0    21-39 km/h              Windy
 12             13     0.4179           28.0    21-39 km/h              Windy
 13             14     0.3881           26.0    21-39 km/h              Windy
 14             15     0.1045            7.0     6-20 km/h             Breeze
 15             16     0.4925           33.0    21-39 km/h              Windy
 16             17     0.5522           37.0    21-39 km/h              Windy
 17             18     0.4627           31.0    21-39 km/h              Windy
 18             19     0.5224           35.0    21-39 km/h              Windy
 19             20     0.5821           39.0    21-39 km/h              Windy
 20             21     0.6567           44.0    40-60 km/h        Strong Wind
 21             22     0.6119           41.0    40-60 km/h        Strong Wind
 22             23     0.7761           52.0    40-60 km/h        Strong Wind
 23             24     0.6866           46.0    40-60 km/h        Strong Wind
 24             25     0.7463           50.0    40-60 km/h        Strong Wind
 25             26     0.6418           43.0    40-60 km/h        Strong Wind
 26             27     0.8060           54.0    40-60 km/h        Strong Wind
 27             28     0.8507           57.0    40-60 km/h        Strong Wind
 28             29     0.8358           56.0    40-60 km/h        Strong Wind
 29             30     0.7164           48.0    40-60 km/h        Strong Wind)

In [ ]:
# Additional columns on date dimension table 

def get_dim_dates(df: pd.DataFrame) -> pd.DataFrame:
    us_holidays = holidays.US()

    # Ensure 'date' column is datetime
    df['date'] = pd.to_datetime(df['date'])

    # Day of week category (weekday/weekend)
    df['day_of_week_category'] = df['date'].dt.weekday.apply(
        lambda x: "Weekend" if x in [5, 6] else "Weekday"
    )

    # US holiday flag
    df["Is_public_holiday"] = df['date'].isin(us_holidays).astype(int)

    # Quarter
    df['Quarter'] = df['date'].dt.quarter.map({1: "Q1", 2: "Q2", 3: "Q3", 4: "Q4"})

    # Year-Month (2023-Jan format)
    df['Year_Month'] = df['date'].dt.strftime("%Y-%b")

    return df

In [ ]:
#Get the processed date dimension table
dim_dates_tbl_processed = get_dim_dates(df_dates)

#Check the date dimension table
dim_dates_tbl_processed.dtypes

date                    datetime64[ns]
datekey                          int64
day                              int64
month                            int64
month_name                      object
year                             int64
weekday                         object
weekofyear                       int64
is_weekend                       int64
data_extract_ts                 object
day_of_week_category            object
Is_public_holiday                int32
Quarter                         object
Year_Month                      object
dtype: object

In [42]:
df_bikesharing.columns

Index(['index', 'date', 'season', 'year', 'month', 'hour', 'holiday',
       'weekday', 'workingday', 'weather', 'temp', 'atemp', 'humidity',
       'windspeed', 'casual', 'registered', 'demand', 'data_extract_ts'],
      dtype='object')

In [43]:
#Check the season value counts 
dim_season_tbl_processed

   season_key season_description
0           1             Winter
1           2             Spring
2           3             Summer
3           4             Autumn

In [67]:
bikesharing_df.dtypes

index                int64
date                object
season               int64
year                 int64
month                int64
hour                 int64
holiday              int64
weekday              int64
workingday           int64
weather              int64
temp               float64
atemp              float64
humidity           float64
windspeed          float64
casual               int64
registered           int64
demand               int64
data_extract_ts     object
dtype: object

In [111]:
# #Checking fact date issue

bikesharing_check = bikesharing_df.merge(
    dim_temp_tbl_processed[['temp', 'temp_key']],
    on='temp', 
    how='left'
)

bikesharing_check

,index,date,season,year,month,hour,holiday,weekday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,demand,data_extract_ts,temp_key
0,1,1/01/2023,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0000,3,13,16,2025-11-16 08:20:51,1
1,2,1/01/2023,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0000,8,32,40,2025-11-16 08:20:51,2
2,3,1/01/2023,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0000,5,27,32,2025-11-16 08:20:51,2
3,4,1/01/2023,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0000,3,10,13,2025-11-16 08:20:51,1
4,5,1/01/2023,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0000,0,1,1,2025-11-16 08:20:51,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17374,17375,31/12/2024,1,1,12,19,0,1,1,2,0.26,0.2576,0.60,0.1642,11,108,119,2025-11-16 08:20:51,13
17375,17376,31/12/2024,1,1,12,20,0,1,1,2,0.26,0.2576,0.60,0.1642,8,81,89,2025-11-16 08:20:51,13
17376,17377,31/12/2024,1,1,12,21,0,1,1,1,0.26,0.2576,0.60,0.1642,7,83,90,2025-11-16 08:20:51,13
17377,17378,31/12/2024,1,1,12,22,0,1,1,1,0.26,0.2727,0.56,0.1343,13,48,61,2025-11-16 08:20:51,13
17378,17379,31/12/2024,1,1,12,23,0,1,1,1,0.26,0.2727,0.65,0.1343,12,37,49,2025-11-16 08:20:51,13

In [134]:
# Final create joins between fact and dim tables to get keys   
def get_bikesharing_fact_table(df: pd.DataFrame) -> pd.DataFrame:
   ''' 
   Get bikesharing fact table by merging with dimension tables to get surrogate keys.
   '''
    # Get dimension tables
    # Merge to get keys
   
   fact_df = df.copy()

   fact_df = fact_df.merge(
    dim_temp_tbl_processed[['temp', 'temp_key']],
    on='temp', 
    how='left'
) 
  
     
   fact_df = fact_df.merge(
    dim_humidity_tbl_processed[['humidity', 'humidity_key']],
    on='humidity',
    how='left'
)
  
   fact_df = fact_df.merge(
    dim_windspeed_tbl_processed[['windspeed', 'windspeed_key']]
    ,on='windspeed',
    how='left'  
)
   
   fact_df = fact_df.merge(
    dim_season_tbl_processed[['season_key']],
    left_on='season',
    right_on='season_key',
    how='left'
)
   
   fact_df = fact_df.merge(
     dim_weather_tbl_processed[['weather_key']],
     left_on='weather',
     right_on='weather_key',
     how='left'

    ) 
   
   fact_df = fact_df.merge(
     dim_hour_tbl_processed[['hour' , 'hour_key']],
     on='hour',
     how='left'
    )
   #Ensure 'date' column is datetime
   cols = ['date', 'data_extract_ts']
   for col in cols:
    fact_df[col] = pd.to_datetime(
        fact_df[col], 
        dayfirst=True
    )

   time.sleep(2)  # Small delay to ensure datetime conversion
   fact_df = fact_df.merge(
    dim_dates_tbl_processed[['date', 'datekey']],
    on='date',
    how='left'
 )
   
   # Drop natural columns
   fact_df = fact_df.drop(columns=['temp', 'weekday', 
                              'workingday', 'holiday' , 
                              'atemp', 'humidity','windspeed',
                              'season','weather','hour','date',
                                'year', 'month', 'casual', 'registered'])

   return fact_df[['index', 'temp_key', 'humidity_key', 'windspeed_key', 'season_key',
                   'weather_key', 'hour_key', 'datekey', 'demand', 'data_extract_ts']]

In [137]:
# Preview bikesharing fact table
bikesharing_fact_tbl_processed = get_bikesharing_fact_table(df_bikesharing)
bikesharing_fact_tbl_processed

C:\Users\prati\AppData\Local\Temp\ipykernel_13880\2597378992.py:53: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  fact_df[col] = pd.to_datetime(

,index,temp_key,humidity_key,windspeed_key,season_key,weather_key,hour_key,datekey,demand,data_extract_ts
0,1,1,1,1,1,1,0,20230101,16,2025-11-16 08:20:51
1,2,2,2,1,1,1,1,20230101,40,2025-11-16 08:20:51
2,3,2,2,1,1,1,2,20230101,32,2025-11-16 08:20:51
3,4,1,3,1,1,1,3,20230101,13,2025-11-16 08:20:51
4,5,1,3,1,1,1,4,20230101,1,2025-11-16 08:20:51
...,...,...,...,...,...,...,...,...,...,...
17374,17375,13,55,9,1,2,19,20241231,119,2025-11-16 08:20:51
17375,17376,13,55,9,1,2,20,20241231,89,2025-11-16 08:20:51
17376,17377,13,55,9,1,1,21,20241231,90,2025-11-16 08:20:51
17377,17378,13,35,8,1,1,22,20241231,61,2025-11-16 08:20:51
17378,17379,13,56,8,1,1,23,20241231,49,2025-11-16 08:20:51

In [152]:
# Construct the data for machine learning model 
# The original bikesharing dataset is ml hence replicating the same structure   
bikesharing_ml_processed = pd.read_parquet(bronze_folder_path + "/bikesharing.parquet")

In [ ]:
# Create dictionary and use forloop of dataframes to save in silver folderpath as processed files 

processed_dfs = {
    "bikesharing_fact_tbl_processed": bikesharing_fact_tbl_processed,
    "dim_season_tbl_processed": dim_season_tbl_processed,
    "dim_weather_tbl_processed": dim_weather_tbl_processed,
    "dim_hour_tbl_processed": dim_hour_tbl_processed,
    "dim_temp_tbl_processed": dim_temp_tbl_processed,
    "dim_humidity_tbl_processed": dim_humidity_tbl_processed,
    "dim_windspeed_tbl_processed": dim_windspeed_tbl_processed,
    "dim_dates_tbl_processed": dim_dates_tbl_processed,
    "bikesharing_ml_processed": bikesharing_ml_processed
    
}

In [143]:
# Create function to save all processed dataframes into silver layer as csv files
def save_to_silver(processed_dfs: dict, silver_folder_path: str):
    """
    Save all processed dataframes into the Silver layer as CSV files.
    """

    # Ensure folder exists
    os.makedirs(silver_folder_path, exist_ok=True)

    for name, df in processed_dfs.items():

        file_path = os.path.join(silver_folder_path, f"{name}.csv")
        silver_path = os.path.relpath(file_path)
        try:
            df.to_csv(file_path, index=False, encoding="utf-8")
            print(f"✅ Saved {name} to Silver layer at {silver_path}")

        except Exception as e:
            print(f"❌ Failed to save {name}: {e}")

In [ ]:
# # Check the saved fact table from silver layer
# df_fact = pd.read_csv(silver_folder_path + "/bikesharing_fact_tbl_processed.csv", encoding="utf-8") 
# df_fact.head()

,index,temp_key,humidity_key,windspeed_key,season_key,weather_key,hour_key,datekey,demand,data_extract_ts
0,1,1,1,1,1,1,0,20230101,16,2025-11-16 08:20:51
1,2,2,2,1,1,1,1,20230101,40,2025-11-16 08:20:51
2,3,2,2,1,1,1,2,20230101,32,2025-11-16 08:20:51
3,4,1,3,1,1,1,3,20230101,13,2025-11-16 08:20:51
4,5,1,3,1,1,1,4,20230101,1,2025-11-16 08:20:51

In [ ]:
# # Check ML table
# df_ml = pd.read_csv(silver_folder_path + "/bikesharing_ml_processed.csv", encoding="utf-8")
# df_ml.head()

,index,date,season,year,month,hour,holiday,weekday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,demand,data_extract_ts
0,1,1/01/2023,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,3,13,16,2025-11-16 08:20:51
1,2,1/01/2023,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0,8,32,40,2025-11-16 08:20:51
2,3,1/01/2023,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0,5,27,32,2025-11-16 08:20:51
3,4,1/01/2023,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0,3,10,13,2025-11-16 08:20:51
4,5,1/01/2023,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0,0,1,1,2025-11-16 08:20:51

In [ ]:
logging.info("Saving datasets to Silver layer...")
try:
    save_to_silver(processed_dfs, silver_folder_path)
    
    logging.info("Datasets saved to Silver layer successfully.")
except Exception as e:
    logging.error(f"Failed to save datasets to Silver layer: {e}")
    raise

# Constructing Gold Layer  
The gold layer would be simple table and change of name from processed to curated

In [ ]:
# Create list and use forloop of dataframes to save in silver folderpath as processed files 

def promote_silver_to_gold(silver_folder_path, gold_folder_path):
    # Ensure gold folder exists
    os.makedirs(gold_folder_path, exist_ok=True)

    # Loop over every CSV in silver
    for file_name in os.listdir(silver_folder_path):

        if file_name.endswith(".csv"):

            # Build full file paths
            silver_file = os.path.join(silver_folder_path, file_name)

            # Replace "processed" with "curated"
            gold_file_name = file_name.replace("_processed", "_curated")
            gold_file = os.path.join(gold_folder_path, gold_file_name)

            # Read → write
            df = pd.read_csv(silver_file, encoding="utf-8-sig")
            df.to_csv(gold_file, index=False, encoding="utf-8-sig")

            print(f"Promoted to GOLD: {gold_file_name}")

In [ ]:
logging.info("Saving datasets to Gold layer...")
try:
    promote_silver_to_gold(silver_folder_path, gold_folder_path)
    
    logging.info("Datasets saved to Gold layer successfully.")
except Exception as e:
    logging.error(f"✔ Failed to save datasets to Gold layer: {e}")
    raise

✔ Promoted to GOLD: bikesharing_fact_tbl_curated.csv
✔ Promoted to GOLD: bikesharing_ml_curated.csv
✔ Promoted to GOLD: dim_dates_tbl_curated.csv
✔ Promoted to GOLD: dim_hour_tbl_curated.csv
✔ Promoted to GOLD: dim_humidity_tbl_curated.csv
✔ Promoted to GOLD: dim_season_tbl_curated.csv
✔ Promoted to GOLD: dim_temp_tbl_curated.csv
✔ Promoted to GOLD: dim_weather_tbl_curated.csv
✔ Promoted to GOLD: dim_windspeed_tbl_curated.csv

In [ ]:
# # Testing the gold layer files  
# df_gold = pd.read_csv(gold_folder_path + "/bikesharing_fact_tbl_curated.csv", encoding="utf-8")
# df_gold.head()

,index,temp_key,humidity_key,windspeed_key,season_key,weather_key,hour_key,datekey,demand,data_extract_ts
0,1,1,1,1,1,1,0,20230101,16,2025-11-16 08:20:51
1,2,2,2,1,1,1,1,20230101,40,2025-11-16 08:20:51
2,3,2,2,1,1,1,2,20230101,32,2025-11-16 08:20:51
3,4,1,3,1,1,1,3,20230101,13,2025-11-16 08:20:51
4,5,1,3,1,1,1,4,20230101,1,2025-11-16 08:20:51